import { canonicalSerialize } from "../canonical/canonicalValueSerialization";
import { validateShadowOperatorCommand, validateShadowOperatorCommandReceipt, type ShadowOperatorCommand, type ShadowOperatorCommandReceipt, type ShadowOperatorCommandRepository } from "./shadowOperatorControls";

export const SHADOW_OPERATOR_CONTROL_DB_NAME = "gotrader-v2-shadow-operator-controls";
export const SHADOW_OPERATOR_CONTROL_DB_VERSION = 1;
const COMMANDS = "commands"; const RECEIPTS = "receipts";
const requestResult = <T>(request: IDBRequest<T>) => new Promise<T>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
const transactionDone = (tx: IDBTransaction) => new Promise<void>((resolve, reject) => { tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error); });
const exact = (a: unknown, b: unknown) => canonicalSerialize(a) === canonicalSerialize(b);
const open = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(SHADOW_OPERATOR_CONTROL_DB_NAME, SHADOW_OPERATOR_CONTROL_DB_VERSION); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(COMMANDS)) request.result.createObjectStore(COMMANDS, { keyPath: "commandId" }); if (!request.result.objectStoreNames.contains(RECEIPTS)) request.result.createObjectStore(RECEIPTS, { keyPath: "commandId" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });

export class IndexedDbShadowOperatorCommandRepository implements ShadowOperatorCommandRepository {
  async claim(command: Readonly<ShadowOperatorCommand>) { if (!await validateShadowOperatorCommand(command)) throw new Error("Shadow operator command identity rejected."); const db = await open(); try { const tx = db.transaction([COMMANDS, RECEIPTS], "readwrite"); const receipt = await requestResult<ShadowOperatorCommandReceipt | undefined>(tx.objectStore(RECEIPTS).get(command.commandId)); if (receipt) { await transactionDone(tx); return receipt; } const existing = await requestResult<ShadowOperatorCommand | undefined>(tx.objectStore(COMMANDS).get(command.commandId)); if (existing) { if (!exact(existing, command)) throw new Error("Shadow operator command conflict."); await transactionDone(tx); return "in_progress" as const; } tx.objectStore(COMMANDS).add(command); await transactionDone(tx); return "claimed" as const; } finally { db.close(); } }
  async complete(command: Readonly<ShadowOperatorCommand>, receipt: Readonly<ShadowOperatorCommandReceipt>) { if (!await validateShadowOperatorCommandReceipt(receipt) || receipt.commandId !== command.commandId) throw new Error("Shadow operator command receipt identity rejected."); const db = await open(); try { const tx = db.transaction([COMMANDS, RECEIPTS], "readwrite"); const current = await requestResult<ShadowOperatorCommand | undefined>(tx.objectStore(COMMANDS).get(command.commandId)); if (!current || !exact(current, command)) throw new Error("Shadow operator command claim is unavailable."); const existing = await requestResult<ShadowOperatorCommandReceipt | undefined>(tx.objectStore(RECEIPTS).get(command.commandId)); if (existing && !exact(existing, receipt)) throw new Error("Shadow operator command receipt conflict."); if (!existing) tx.objectStore(RECEIPTS).add(receipt); await transactionDone(tx); } finally { db.close(); } }
  async receipt(commandId: string) { const db = await open(); try { const tx = db.transaction([RECEIPTS], "readonly"); const value = await requestResult<ShadowOperatorCommandReceipt | undefined>(tx.objectStore(RECEIPTS).get(commandId)); await transactionDone(tx); return value; } finally { db.close(); } }
}
